package(default_visibility = ["//mediapipe/examples:__subpackages__"])
cc_binary(
    name = "libmy.so",
    srcs = ["SoDemoTest.h","one.cpp","two.cpp","three.cpp"],
    deps = [],
    linkshared=True,
)
